resources:
  database:
    type: postgres
    options:
      storage: 10
  redis:
    type: redis
  memcached:
    type: memcached
  mysql:
    type: mysql
    options:
      storage: 10
services:
  app:
    build: .
    scale:
      count: 0
    resources:
      - database
      - redis
      - memcached
      - mysql
    test: ./run.sh

